apiVersion: v1
kind: Pod
metadata:
  name: zk-gszopin-pod
  labels:
    app: zk-gszopin
spec:
  containers:
  - name: zk-gszopin
    image: gszopinski123/zk-gszopin:zookeeper
    command: ["/bin/bash", "-c"]
    args: [
      "expr $(echo $(hostname) | awk -F 'sset-' '{print $2}') + 1 > /zookeeper/zookeeper-data/myid",
      "./apache-zookeeper-3.9.3-bin/bin/zkServer.sh start-foreground"
      ]
    ports:
    - containerPort: 2181